[tasks.build]
command = "cargo"
args = ["build", "--features", "mcu-STM32L051C8Tx,rt", "--release", "--example", "${@}"]

[tasks.flash]
command = "JRunExe"
args = ["-device", "STM32L051C8", "-if", "SWD", "--semihost", "target/thumbv6m-none-eabi/release/examples/${@}"]
dependencies = ["build"]
