[tasks.build]
command = "cargo"
args = ["build", "--features", "mcu-STM32L051C8Tx,rt", "--release", "--example", "${@}"]

[tasks.flash]
command = "./openocd_flash.sh"
args = ["target/thumbv6m-none-eabi/release/examples/${@}"]
dependencies = ["build"]
